# Your Website Title
title: Вселенная Сусликов

# Your Website URL
url: 'https://ganiev-timur.ru'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Иван Сусанин
tagline: Права сусликов важны, права сусликов нужны!
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Права сусликов важны, права сусликов нужны!
description_tiny: 'Защитите их мохнатые задницы!'
email: info@ganiev-timur.ru
website: melvinchng.github.io # do not add http://
linkedin: realmelvinchng
github: melvinchng
twitter: '@realmelvinchng'
vk: vk.com

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
    #  - wdm
